#!/bin/bash

_SCRIPT="${BASH_SOURCE[0]}"
while [ -L "$_SCRIPT" ]; do _SCRIPT="$(readlink "$_SCRIPT")"; done
DIR="$(cd "$(dirname "$_SCRIPT")" && pwd)"
source "$DIR/../venv/bin/activate"
exec python3 -W ignore "$DIR/../src/sre.py" "$@"
